---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-test-prod
  namespace: argocd
spec:
  project: kili-test
  source:
    repoURL: https://github.com/discostur/argo-test.git
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 