---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-test-dev
  namespace: argocd
spec:
  project: kili-test
  source:
    repoURL: https://github.com/discostur/argo-test.git
    targetRevision: HEAD
    path: ArgoCD/kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 