---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-chart
  namespace: argocd
spec:
  project: kili-test
  destination:
    server: https://kubernetes.default.svc
    namespace: example-chart
  sources:
    - repoURL: https://github.com/discostur/argo-test.git
      path: ArgoCD/helm-charts/example-chart
      targetRevision: main
      helm:
        releaseName: example-chart
        valueFiles:
          - $values/ArgoCD/helm-charts/example-chart/values.yaml
    - repoURL: https://github.com/discostur/argo-test.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true 
