apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  path: ./FluxCD/fleet-infra
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-repo
  suspend: false
  timeout: 2m0s
  wait: true
