# Default values for example-chart

replicaCount: 1

releaseIdentifier: 123

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
