apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: kustomize-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 400m

commonLabels:
  environment: production 
  app: kustomize-deployment
