---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: nginx-ingress
      version: "1.9.1"  # Setze die gewünschte Version
      sourceRef:
        kind: GitRepository
        name: flux-repo
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  suspend: true  # Verhindert automatische Deployments
