apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: kustomize-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 100m

commonLabels:
  environment: development 
  app: kustomize-deployment